#!/usr/bin/env bash
# build.sh - cross-compile a mix-and-match patch DLL on macOS with zig cc.
#
#   ./build.sh <plugin> [plugin ...]      build a DLL with the named plugins
#   ./build.sh --list                     list available plugins
#
# Each <plugin> is a directory under plugins/ containing plugin.c with a
# PK_PLUGIN(<plugin>) definition.  The output is named after the proxy target
# (default iphlpapi.dll); drop it next to diabotical.exe.
#
# Env overrides:
#   ZIG=/path/to/zig     PROXY=iphlpapi     OUT=./build
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ZIG="${ZIG:-zig}"; command -v "$ZIG" >/dev/null 2>&1 || ZIG=/usr/local/bin/zig
PROXY="${PROXY:-gfsdk}"   # gfsdk: cross-platform (Win+Proton); iphlpapi: Windows-only
OUT="${OUT:-$HERE/build}"
TARGET="x86_64-windows-gnu"

if [ "${1:-}" = "--list" ] || [ $# -eq 0 ]; then
    echo "available plugins:"
    for d in "$HERE"/plugins/*/; do echo "  - $(basename "$d")"; done
    echo
    echo "usage: $(basename "$0") <plugin> [plugin ...]"
    [ $# -eq 0 ] && exit 1 || exit 0
fi

PROXY_SRC="$HERE/src/proxy_${PROXY}.c"
[ -f "$PROXY_SRC" ] || { echo "error: no proxy src for '$PROXY' ($PROXY_SRC)"; exit 1; }

# A proxy source may declare, via marker lines, the filename it must deploy as
# (the DLL the game imports by name) and the rename step for the original:
#   PK-DEPLOY-AS: <name>.dll
#   PK-RENAME-ORIG: <orig>.dll -> <renamed>.dll
# Default deploy name is "<PROXY>.dll" (the iphlpapi case, where they coincide).
DEPLOY_AS="$(sed -n 's/.*PK-DEPLOY-AS:[[:space:]]*\([^[:space:]]*\).*/\1/p' "$PROXY_SRC" | head -1)"
DEPLOY_AS="${DEPLOY_AS:-${PROXY}.dll}"
RENAME_ORIG="$(sed -n 's/.*PK-RENAME-ORIG:[[:space:]]*\(.*\)/\1/p' "$PROXY_SRC" | head -1)"

mkdir -p "$OUT"
REG="$OUT/pk_registry.c"
{
    echo '/* generated by build.sh - do not edit */'
    echo '#include "patchkit.h"'
    for p in "$@"; do echo "extern int pk_init_${p}(void);"; done
    echo 'const pk_plugin pk_plugins[] = {'
    for p in "$@"; do echo "    { \"${p}\", pk_init_${p} },"; done
    echo '};'
    echo "const int pk_plugin_count = $#;"
} > "$REG"

SRCS=( "$HERE/src/loader.c" "$HERE/src/patchkit.c" "$HERE/src/console_banner.c" "$PROXY_SRC" "$REG" )
for p in "$@"; do
    f="$HERE/plugins/$p/plugin.c"
    [ -f "$f" ] || { echo "error: no such plugin '$p' ($f)"; exit 1; }
    SRCS+=( "$f" )
done

"$ZIG" cc -target "$TARGET" -shared -O2 -Wall \
    -I"$HERE/include" \
    -o "$OUT/${DEPLOY_AS}" "${SRCS[@]}" \
    -lkernel32

echo "[+] built $OUT/${DEPLOY_AS}"
echo "    proxy   : ${PROXY}  (deploys as ${DEPLOY_AS})"
echo "    plugins : $*"
echo "    deploy  :"
if [ -n "$RENAME_ORIG" ]; then
    echo "      1. in the game folder, rename:  ${RENAME_ORIG}"
    echo "      2. copy $OUT/${DEPLOY_AS} next to diabotical.exe"
    echo "      (works on Windows AND Linux/Proton - no launch options)"
else
    echo "      back up any existing ${DEPLOY_AS} in the game folder, then copy this next to diabotical.exe"
fi
echo "    runtime log: patchkit.log next to the DLL"
